#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100


file="school"

if [ -e "$file" ]; then
    echo "school file exists"
    
    if [ -s "$file" ]; then
        echo "school file is not empty"
        
        if [ -f "$file" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi

