#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username password userid groupid user_info homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

