#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# if 9 say Hi

counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
