#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# The while loop iterates from 1 to 10
# The if, elif, and else statements check the current iteration and print the c# orresponding message ("Bad Luck," "Good Luck," or "Best School")

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad Luck"
    elif [ $counter -eq 8 ]; then
        echo "good Luck"
    else
        echo "Best School"
    fi
    ((counter++))

done
