#!/usr/bin/env bash
# This script that displays numbers from 1 to 10
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then Bad Luck from China"
            ;;
        9)
            echo "$counter and then Bad Luck from Japan"
            ;;
        17)
            echo "$counter and then Bad Luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
