#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
## except for TCP ports 22, 443 and 80.



#ensure ufw is installed and check status
sudo ufw status

#enable ufw if not active
sudo ufw enable

#set default policy to deny all incoming traffic
sudo ufw default deny incoming

#allow the specified ports in the task
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#check the rules that have been set
sudo ufw status numbered

#reload ufw to apply the changes
sudo ufw reload

