#!/usr/bin/env bash
#  Bash script that displays all active IPv4 IPs on the machine it’s executed on

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Please use sudo."
    exit 1
fi

cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" >> /etc/hosts

echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Configuration completed. /etc/hosts has been updated."

cat /etc/hosts

#!/bin/bash

# Use ifconfig to get active IPv4 addresses and extract them with awk
ipv4_addresses=$(ifconfig | awk '/inet / {print $2}')

echo "Active IPv4 Addresses:"
echo "$ipv4_addresses"

