#!/usr/bin/env bash
# Bash script that Write a Bash script that listens on port 98 on localhost

ipv4_addresses=$(ifconfig | awk '/inet / {print $2}')

echo "Active IPv4 Addresses:"
echo "$ipv4_addresses"


if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Please use sudo."
    exit 1
fi

nc -l -p 98